### ISSUE TITLE
error pas pull

### ISSUE THREAD

**Issue by ryuu9** [k1m0ch1/covid-19-api#3]
ane masih newbie yg baru nyoba docker. kenapa pas di pull error 
`Unable to find image 'docker.pkg.github.com/k1m0ch1/covid-19-api/covid-19-api:latest' locally
docker: Error response from daemon: Get https://docker.pkg.github.com/v2/k1m0ch1/covid-19-api/covid-19-api/manifests/latest: no basic auth credentials.
See 'docker run --help'.`

**Comment by k1m0ch1** [comment]
sorry bro, dokumentasi nya belum update, daripada pake `docker.pkg.github.com/k1m0ch1/covid-19-api/covid-19-api:lates` lu bisa pake `k1m0ch1/covid-19-api` bisa di cek di link ini https://hub.docker.com/repository/docker/k1m0ch1/covid-19-api
